from pptx.enum.shapes import MSO_SHAPE_TYPE

def check (shape_type):
	if shape_type == MSO_SHAPE_TYPE.AUTO_SHAPE: return 'AutoShape'
	if shape_type == MSO_SHAPE_TYPE.CALLOUT: return 'Callout shape'
	if shape_type == MSO_SHAPE_TYPE.CANVAS: return 'Drawing canvas'
	if shape_type == MSO_SHAPE_TYPE.CHART: return 'Chart, e.g. pie chart, bar chart'
	if shape_type == MSO_SHAPE_TYPE.COMMENT: return 'Comment'
	if shape_type == MSO_SHAPE_TYPE.DIAGRAM: return 'Diagram'
	if shape_type == MSO_SHAPE_TYPE.EMBEDDED_OLE_OBJECT: return 'Embedded OLE object'
	if shape_type == MSO_SHAPE_TYPE.FORM_CONTROL: return 'Form control'
	if shape_type == MSO_SHAPE_TYPE.FREEFORM: return 'Freeform'
	if shape_type == MSO_SHAPE_TYPE.GROUP: return 'Group shape'
	if shape_type == MSO_SHAPE_TYPE.IGX_GRAPHIC: return 'SmartArt graphic'
	if shape_type == MSO_SHAPE_TYPE.INK: return 'Ink'
	if shape_type == MSO_SHAPE_TYPE.INK_COMMENT: return 'Ink Comment'
	if shape_type == MSO_SHAPE_TYPE.LINE: return 'Line'
	if shape_type == MSO_SHAPE_TYPE.LINKED_OLE_OBJECT: return 'Linked OLE object'
	if shape_type == MSO_SHAPE_TYPE.LINKED_PICTURE: return 'Linked picture'
	if shape_type == MSO_SHAPE_TYPE.MEDIA: return 'Media'
	if shape_type == MSO_SHAPE_TYPE.OLE_CONTROL_OBJECT: return 'OLE control object'
	if shape_type == MSO_SHAPE_TYPE.PICTURE: return 'Picture'
	if shape_type == MSO_SHAPE_TYPE.PLACEHOLDER: return 'Placeholder'
	if shape_type == MSO_SHAPE_TYPE.SCRIPT_ANCHOR: return 'Script anchor'
	if shape_type == MSO_SHAPE_TYPE.TABLE: return 'Table'
	if shape_type == MSO_SHAPE_TYPE.TEXT_BOX: return 'Text box'
	if shape_type == MSO_SHAPE_TYPE.TEXT_EFFECT: return 'Text effect'
	if shape_type == MSO_SHAPE_TYPE.WEB_VIDEO: return 'Web video'
	if shape_type == MSO_SHAPE_TYPE.MIXED: return 'Mixed shape types'